import type {
  StudyMethod,
  TimerMode,
  WorkspaceSettings,
  WorkspaceState,
} from "@/lib/types";
import { createId } from "@/lib/ids";

export const DEFAULT_TIMER_MODES: TimerMode[] = [
  { id: "micro", label: "Micro 15/3", focus: 15, break: 3, enabled: true },
  {
    id: "pomodoro",
    label: "Pomodoro 25/5",
    focus: 25,
    break: 5,
    enabled: true,
  },
  { id: "sprint", label: "Study 40/8", focus: 40, break: 8, enabled: true },
  { id: "exam", label: "Exam 45/10", focus: 45, break: 10, enabled: true },
  {
    id: "balanced",
    label: "Balanced 50/10",
    focus: 50,
    break: 10,
    enabled: true,
  },
  { id: "flow52", label: "Flow 52/17", focus: 52, break: 17, enabled: true },
  {
    id: "ultradian",
    label: "Ultradian 75/15",
    focus: 75,
    break: 15,
    enabled: true,
  },
  { id: "deep", label: "Deep Work 90/20", focus: 90, break: 20, enabled: true },
  { id: "recall", label: "Recall 12/3", focus: 12, break: 3, enabled: true },
  {
    id: "flowtime",
    label: "Flowtime",
    focus: 0,
    break: 8,
    countUp: true,
    enabled: true,
  },
  {
    id: "stopwatch",
    label: "Stoper",
    focus: 0,
    break: 0,
    countUp: true,
    enabled: true,
  },
  { id: "custom", label: "Własny 35/8", focus: 35, break: 8, enabled: true },
];

export const DEFAULT_STUDY_METHOD_MINUTES: Record<StudyMethod, number> = {
  feynman: 15,
  blurting: 10,
  cornell: 20,
  interleaving: 18,
  "exam-sprint": 25,
  leitner: 12,
};

export const DEFAULT_WORKSPACE_SETTINGS: WorkspaceSettings = {
  theme: "system",
  accent: "sage",
  fontScale: "comfortable",
  density: "comfortable",
  reducedMotion: false,
  defaultView: "home",
  shortcutLinks: [
    { id: "shortcut-focus", kind: "view", view: "focus", label: "Rozpocznij focus", category: "Skupienie", enabled: true },
    { id: "shortcut-tasks", kind: "view", view: "tasks", label: "Moje zadania", category: "Organizacja", enabled: true },
    { id: "shortcut-learn", kind: "view", view: "learn", label: "Powtórki", category: "Nauka", enabled: true },
    { id: "shortcut-planner", kind: "view", view: "planner", label: "Plan dnia", category: "Organizacja", enabled: true },
  ],
  showDashboardShortcuts: true,
  dashboardShortcutLimit: 8,
  showCompletedTasks: true,
  confirmBeforeDelete: true,
  taskSort: "smart",
  defaultSubjectId: "",
  defaultTaskEstimate: 25,
  defaultTaskPriority: 2,
  defaultTaskDifficulty: 2,
  defaultTaskRecurring: "none",
  timerModes: DEFAULT_TIMER_MODES,
  defaultTimerMode: "pomodoro",
  autoStartBreak: false,
  autoStartFocus: false,
  adaptiveBreaks: true,
  fullscreenOnTimerStart: true,
  exitFullscreenOnPause: true,
  minimalFocusMode: false,
  longBreakMinutes: 20,
  keepScreenAwake: true,
  notifications: true,
  adaptiveFocusDuration: true,
  autoPauseWhenIdle: false,
  idleMinutes: 5,
  focusShield: false,
  blockedDomains: [],
  showPictureInPicture: true,
  longBreakAfter: 4,
  enabledStudyMethods: [
    "feynman",
    "blurting",
    "cornell",
    "interleaving",
    "exam-sprint",
    "leitner",
  ],
  studyMethodMinutes: DEFAULT_STUDY_METHOD_MINUTES,
  showStudyMethodGuides: true,
  dailyFocusGoalMinutes: 90,
  dailyReviewGoal: 20,
  reviewLimit: 50,
  reviewOrder: "smart",
  defaultDeck: "Ogólne",
  flipCardOnClick: true,
  plannerDefaultMode: "week",
  defaultBlockMinutes: 50,
  workdayStartHour: 7,
  workdayEndHour: 21,
  weekStartsOn: 1,
  autoSync: true,
  syncIntervalSeconds: 30,
  appLockEnabled: false,
  lockAfterMinutes: 15,
  biometricLockEnabled: false,
  encryptedBackups: true,
  automaticDailyBackup: true,
};

export function createDefaultWorkspace(): WorkspaceState {
  const now = new Date().toISOString();
  return {
    schemaVersion: 5,
    syncId: createId(),
    version: 1,
    syncedVersion: 0,
    updatedAt: now,
    syncRevision: 0,
    tombstones: [],
    tasks: [],
    subjects: [],
    flashcards: [],
    exams: [],
    calendar: [],
    habits: [],
    sessions: [],
    materials: [],
    studyRuns: [],
    reviewActivity: [],
    flashcardReviews: [],
    projects: [],
    quizzes: [],
    quizAttempts: [],
    mistakes: [],
    studyNotes: [],
    journalEntries: [],
    challenges: [],
    rewards: [],
    notificationSchedules: [],
    trash: [],
    activityLog: [],
    progress: {
      xp: 0,
      spentXp: 0,
      streakShields: 2,
      usedShields: 0,
      unlockedBadges: [],
    },
    focusQueue: [],
    settings: {
      ...DEFAULT_WORKSPACE_SETTINGS,
      timerModes: DEFAULT_TIMER_MODES.map((mode) => ({ ...mode })),
      shortcutLinks: DEFAULT_WORKSPACE_SETTINGS.shortcutLinks.map((link) => ({
        ...link,
      })),
      enabledStudyMethods: [...DEFAULT_WORKSPACE_SETTINGS.enabledStudyMethods],
      studyMethodMinutes: { ...DEFAULT_STUDY_METHOD_MINUTES },
    },
  };
}
